# docker-compose.wg-easy.yml
version: "3.8"

services:
  wg-easy:
    environment:
      # Server's hostname
      - WG_HOST=jorlo2.ddns.net

      # Web UI Password Hash
      - PASSWORD_HASH=$$2a$$12$$BC3O6oqAAgN/yS14zsIlp.GD/YzzJ1L.oJF9fXsVn7e2AbSSeC/IW

      # Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
